name: Build and Push Docker image to GCP

on:
  push:
    branches:
      - main  # or any branch you want to trigger this action

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STACK: ${{ vars.STACK }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Google Cloud Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker
          
      - name: Build and Push Backend Docker image to GCP
        run: |
          IMAGE_NAME=gcr.io/deploy-box/${{ env.STACK }}-backend
          docker build -t $IMAGE_NAME source_code/backend
          docker push $IMAGE_NAME

      - name: Build and Push Frontend Docker image to GCP
        run: |
          IMAGE_NAME=gcr.io/deploy-box/${{ env.STACK }}-frontend
          docker build -t $IMAGE_NAME source_code/frontend
          docker push $IMAGE_NAME
