name: Build and Push Docker image to GCP

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    env:
      STACK: ${{ vars.STACK }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker
          
      - name: Build and Push Backend Docker image to GCP
        run: |
          IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.STACK }}-backend
          docker build -t $IMAGE_NAME source_code/backend
          docker push $IMAGE_NAME

      - name: Build and Push Frontend Docker image to GCP
        run: |
          IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.STACK }}-frontend
          docker build -t $IMAGE_NAME source_code/frontend
          docker push $IMAGE_NAME
